spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        output:
          binder: kafka
          destination: fuellid-city

server:
  port: 8081
  servlet:
    context-path: /event/api/v1
